### PR TITLE
Use GAMS file from submodule

### PR DESCRIPTION
**Pull request by absolute-afloat**
To avoid duplicate files which have the risk of falling out of sync, use the actual GAMS file from the submodule.

This PR contains formatting of the GAMS code. The testing we currently have only tests some options but there is some GAMS code that might be broken by wrong formatting, which is not discovered by the current testing procedure (e.g. unit committment code).

Further it uses an older version of the GAMS submodule because the current main throws domain violation errors, possibly because of the NUTS2 code.

### CODE REVIEW

**Review by tobiasvh15 — CHANGES_REQUESTED** [review]
Remove 4_model_code_shared. Add documentation on how to get git submodule working.

**Comment by James-Price** [comment]
> Remove 4_model_code_shared. Add documentation on how to get git submodule working.

My understanding is that 4_model_code_shared is in the config file so is essentially user defined - it just needs to be changed there.

**Comment by tobiasvh15** [comment]
> My understanding is that 4_model_code_shared is in the config file so is essentially user defined - it just needs to be changed there.

Yes, the idea was to remove the folder '4_model_code_shared' from the highRES-Europe-WF, as the GAMS files in this folder are just duplicates of what is in the highRES-Europe-GAMS respository.

> On the documentation, not sure what this is? Be good to get this closed and merged though.

The README must be updated with instructions on how to set up the model with the GAMS submodule. With this pull request the model won't run if the current instructions are followed.

**Review by OskarVagero — COMMENTED** [review]
Same story here, discussed at hackathon 2 July 2024.

**Review by OskarVagero — APPROVED** [review]

**Pull request merged**
